package acervo;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabriel
 */
public class BuscaLivros extends javax.swing.JFrame {

    private final Integer colID     = 0;
    private final Integer colTitulo = 1;
    private final Integer colAutor  = 2;
    private final Integer colDelete = 3;
    
    private Livros livros;
    private ArrayList<Livro> listaLivros;
    private DefaultTableModel model;
    
    /**
     * Creates new form BuscaLivros
     */
    public BuscaLivros(Livros livros) {
        
        initComponents();
        this.configTable();

        this.livros = livros;
        
        try {

            this.buscarLivros("");

        } catch (SQLException ex) {
            Dialogs.erro(ex.getMessage(), "Erro durante busca");
        }
        
    }
    
    
    private void configTable() {

        this.model = (DefaultTableModel) this.listagem.getModel();
        this.listagem.getColumnModel().getColumn(this.colID).setPreferredWidth(10);
        this.listagem.getColumnModel().getColumn(this.colTitulo).setPreferredWidth(206);
        this.listagem.getColumnModel().getColumn(this.colAutor).setPreferredWidth(206);
        this.listagem.getColumnModel().getColumn(this.colDelete).setPreferredWidth(30);
        this.listagem.setRowHeight(40);

    }
    
    
    /**
     * Adiciona uma linha na listagem
     * @param livro 
     */
    private void addRowLivro(Livro livro) {
        
        this.model.addRow(new Object[]{
            livro.getId(),
            livro.getTitulo(),
            livro.getAutor(),
            false
        });
        
    }
    

    /**
     * 
     * @param termo
     * @throws SQLException 
     */
    private void buscarLivros(String termo) throws SQLException {

        this.listaLivros = livros.buscar(termo);

        this.model.setRowCount(0);

        this.listaLivros.forEach(livro -> {
            this.addRowLivro(livro);
        });

    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelBusca = new javax.swing.JLabel();
        labelBuscaPor = new javax.swing.JLabel();
        busca = new javax.swing.JTextField();
        btnBusca = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listagem = new javax.swing.JTable();
        btnLimpaBusca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Busca livros");
        setResizable(false);

        labelBusca.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        labelBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/acervo/imagens/book_24x24.png"))); // NOI18N
        labelBusca.setText("Busca livros");

        labelBuscaPor.setText("Buscar pot título ou por autor:");

        btnBusca.setText("Buscar");
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleBuscaLivros(evt);
            }
        });

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechar(evt);
            }
        });

        listagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Título", "Autor", "Excluir"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listagem.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listagem.getTableHeader().setResizingAllowed(false);
        listagem.getTableHeader().setReorderingAllowed(false);
        listagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apagarLivro(evt);
            }
        });
        jScrollPane1.setViewportView(listagem);
        if (listagem.getColumnModel().getColumnCount() > 0) {
            listagem.getColumnModel().getColumn(0).setResizable(false);
            listagem.getColumnModel().getColumn(3).setResizable(false);
        }

        btnLimpaBusca.setText("Limpar busca");
        btnLimpaBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleLimparBusca(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(busca, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(labelBusca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelBuscaPor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(labelBusca)
                .addGap(18, 18, 18)
                .addComponent(labelBuscaPor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(busca))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltar)
                    .addComponent(btnLimpaBusca))
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fechar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechar
        this.dispose();
    }//GEN-LAST:event_fechar

    private void apagarLivro(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apagarLivro
        
        int row = this.listagem.getSelectedRow();
        String titulo = (String) this.listagem.getValueAt(row, this.colTitulo);
        
        if ((boolean) this.listagem.getValueAt(row, this.colDelete)) {
            
            int resp = Dialogs.confirm("Deseja apagar o livro " + titulo, "Apagar livro");
            
            if (resp == 0) {

                try {

                    this.livros.apagar((int) this.listagem.getValueAt(row, this.colID));
                    this.buscarLivros("");

                } catch (Exception ex) {
                    Dialogs.erro(ex.getMessage(), "Erro ao excluir");
                }

            } else {
                this.listagem.setValueAt(false, row, this.colDelete);
            }
        }
    }//GEN-LAST:event_apagarLivro

    private void handleBuscaLivros(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleBuscaLivros

        try {
            this.buscarLivros(this.busca.getText());
        } catch (Exception ex) {
            Dialogs.erro(ex.getMessage(), "Erro ao efetuar busca");
        }

    }//GEN-LAST:event_handleBuscaLivros

    private void handleLimparBusca(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleLimparBusca
        
        this.busca.setText("");

        try {
            this.buscarLivros("");
        } catch (Exception ex) {
            Dialogs.erro(ex.getMessage(), "Erro ao efetuar busca");
        }
        
    }//GEN-LAST:event_handleLimparBusca

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnLimpaBusca;
    private javax.swing.JTextField busca;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBusca;
    private javax.swing.JLabel labelBuscaPor;
    private javax.swing.JTable listagem;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
