/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package acervo;

import java.sql.Connection;
import javax.swing.JTextField;

/**
 *
 * @author gabriel
 */
public class EdicaoUser extends javax.swing.JFrame {

    private Connection conexao;
    private final User usuario;

    /**
     * Creates new form EdicaoUser
     * @param usuario
     */
    public EdicaoUser(User usuario) {

        initComponents();
        this.usuario = usuario;
        this.userNome.setText(usuario.getNome());
        this.userLogin.setText(usuario.getUser());
        this.userSenha.setText(usuario.getSenha());

    }


    public void setConnection(Connection conexao) {
        this.conexao = conexao;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTelaCadastro = new javax.swing.JLabel();
        userNome = new javax.swing.JTextField();
        userLogin = new javax.swing.JTextField();
        fecharEdicao = new javax.swing.JButton();
        cadastroSalvar = new javax.swing.JButton();
        labelSenha = new javax.swing.JLabel();
        labelLogin = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelSenha1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        userSenha = new javax.swing.JPasswordField();
        confirmaSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edição de usuário");
        setResizable(false);

        labelTelaCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/acervo/imagens/user.png"))); // NOI18N
        labelTelaCadastro.setText("Edição de Usuário");

        userLogin.setEditable(false);
        userLogin.setBackground(new java.awt.Color(253, 182, 129));
        userLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                validaTamanhoString(evt);
            }
        });

        fecharEdicao.setText("Cancelar");
        fecharEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleFecharEdicao(evt);
            }
        });

        cadastroSalvar.setText("Salvar");
        cadastroSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edicaoSalvar(evt);
            }
        });

        labelSenha.setText("Senha:");

        labelLogin.setText("Login (edição bloqueada):");

        labelNome.setText("Nome:");

        labelSenha1.setText("Digite sua senha atual para salvar as alterações");

        userSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                validaTamanhoString(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(confirmaSenha)
                    .addComponent(userSenha)
                    .addComponent(jSeparator1)
                    .addComponent(labelTelaCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userNome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userLogin, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(fecharEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cadastroSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelSenha1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(labelTelaCadastro)
                .addGap(18, 18, 18)
                .addComponent(labelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSenha1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecharEdicao)
                    .addComponent(cadastroSalvar))
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void validaTamanhoString(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validaTamanhoString

        JTextField campo = (JTextField) evt.getComponent();

        if (campo.getText().length() > 10) {

            Dialogs.erro("Este campo não pode conter mais de 10 caracteres.", "Erro");
            campo.setText(campo.getText().substring(0, 10));

        }

    }//GEN-LAST:event_validaTamanhoString

    private void handleFecharEdicao(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleFecharEdicao
        this.fecharEdicao();
    }//GEN-LAST:event_handleFecharEdicao

    private void edicaoSalvar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edicaoSalvar

        try {

            String senhaAtual = new String(this.confirmaSenha.getPassword());
            
            if (!this.usuario.validaSenha(senhaAtual)) {
                
                throw new Exception("Senha incorreta! Impossível realizar alteração.");

            }

            this.usuario.setNome(this.userNome.getText());
            this.usuario.setSenha(this.userSenha.getText());

            Users usuarios = new Users(this.conexao);
            usuarios.atualizar(usuario);

            Dialogs.sucesso("Dados alterados com sucesso!", "Sucesso");

            this.fecharEdicao();

        } catch (Exception ex) {
            
            String msg = "Erro :: " + ex.getMessage();
            Dialogs.erro(msg, "Erro");

        }

    }//GEN-LAST:event_edicaoSalvar


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastroSalvar;
    private javax.swing.JPasswordField confirmaSenha;
    private javax.swing.JButton fecharEdicao;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelSenha1;
    private javax.swing.JLabel labelTelaCadastro;
    private javax.swing.JTextField userLogin;
    private javax.swing.JTextField userNome;
    private javax.swing.JPasswordField userSenha;
    // End of variables declaration//GEN-END:variables

    private void fecharEdicao() {

        Perfil perfil = new Perfil(this.usuario);
        perfil.setConnection(this.conexao);
        perfil.setVisible(true);
        
        this.setVisible(false);
        this.dispose();
        
    }
}
