package acervo;

import java.sql.Connection;

/**
 *
 * @author gabriel
 */
public class NovoLivro extends javax.swing.JFrame {

    private Connection conexao;
    private final User usuario;
    
    
    /**
     * Creates new form NovoLivro
     * @param usuario
     */
    public NovoLivro(User usuario) {
        
        initComponents();
        this.usuario = usuario;
        
    }
    
    
    public void setConnection(Connection conexao) {
        this.conexao = conexao;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTituloNovoLivro = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        livroTitulo = new javax.swing.JTextField();
        labelAutor = new javax.swing.JLabel();
        livroAutor = new javax.swing.JTextField();
        salvar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTituloNovoLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/acervo/imagens/book.png"))); // NOI18N
        labelTituloNovoLivro.setText("Novo livro");

        labelTitulo.setText("Título:");

        labelAutor.setText("Autor:");

        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarLivro(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleCancela(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(livroTitulo)
                            .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(livroAutor)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                                .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(labelTituloNovoLivro)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(labelTituloNovoLivro)
                .addGap(18, 18, 18)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(livroTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(labelAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(livroAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvar)
                    .addComponent(cancelar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void handleCancela(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleCancela
        this.dispose();
    }//GEN-LAST:event_handleCancela

    private void salvarLivro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarLivro
        
        Integer userID = this.usuario.getId();
        String titulo = this.livroTitulo.getText();
        String autor = this.livroAutor.getText();
        
        try {
            
            if (userID < 0) {
                throw new Exception("Usuário indefinido!");
            } else if(titulo.isEmpty() || autor.isEmpty()) {
                throw new Exception("Preencha os campos corretamente!");
            }
            
            
            
        } catch (Exception e) {
            
            Dialogs.erro(e.getMessage(), "Erro no cadastro");
            this.dispose();
            
        }
        
    }//GEN-LAST:event_salvarLivro


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel labelAutor;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTituloNovoLivro;
    private javax.swing.JTextField livroAutor;
    private javax.swing.JTextField livroTitulo;
    private javax.swing.JButton salvar;
    // End of variables declaration//GEN-END:variables
}
